// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMarketsRequest {
    /// 分类过滤
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    /// 状态过滤: open, resolved, cancelled
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    /// 排序字段: created_at, end_time, volume
    #[prost(string, tag = "3")]
    pub sort_by: ::prost::alloc::string::String,
    /// 降序
    #[prost(bool, tag = "4")]
    pub descending: bool,
    /// 页码
    #[prost(int32, tag = "5")]
    pub page: i32,
    /// 每页数量
    #[prost(int32, tag = "6")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMarketsResponse {
    #[prost(message, repeated, tag = "1")]
    pub markets: ::prost::alloc::vec::Vec<MarketSummary>,
    #[prost(int64, tag = "2")]
    pub total: i64,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketSummary {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub question: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub category: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub end_time: i64,
    #[prost(string, tag = "5")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub total_volume: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "7")]
    pub outcomes: ::prost::alloc::vec::Vec<OutcomeSummary>,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutcomeSummary {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub volume: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub probability: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetMarketDetailRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMarketDetailResponse {
    #[prost(message, optional, tag = "1")]
    pub market: ::core::option::Option<MarketDetail>,
    #[prost(message, repeated, tag = "2")]
    pub outcomes: ::prost::alloc::vec::Vec<OutcomeDetail>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketDetail {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub question: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub category: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub image_url: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub start_time: i64,
    #[prost(int64, tag = "7")]
    pub end_time: i64,
    #[prost(string, tag = "8")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub total_volume: ::prost::alloc::string::String,
    #[prost(int64, tag = "10")]
    pub resolved_outcome_id: i64,
    #[prost(int64, tag = "11")]
    pub resolved_at: i64,
    #[prost(int64, tag = "12")]
    pub created_at: i64,
    #[prost(int64, tag = "13")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutcomeDetail {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub image_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub volume: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub probability: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOutcomePricesRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    #[prost(int64, repeated, tag = "2")]
    pub outcome_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOutcomePricesResponse {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    #[prost(message, repeated, tag = "2")]
    pub prices: ::prost::alloc::vec::Vec<OutcomePrice>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutcomePrice {
    #[prost(int64, tag = "1")]
    pub outcome_id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub volume: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub probability: ::prost::alloc::string::String,
    /// 24h 价格变化
    #[prost(string, tag = "6")]
    pub change_24h: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetOrderBookRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    /// 深度档位数量
    #[prost(int32, tag = "2")]
    pub depth: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrderBookResponse {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    /// 买盘
    #[prost(message, repeated, tag = "2")]
    pub bids: ::prost::alloc::vec::Vec<OrderBookLevel>,
    /// 卖盘
    #[prost(message, repeated, tag = "3")]
    pub asks: ::prost::alloc::vec::Vec<OrderBookLevel>,
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookLevel {
    #[prost(string, tag = "1")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub quantity: ::prost::alloc::string::String,
    /// 订单数量
    #[prost(string, tag = "3")]
    pub orders: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKlinesRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    /// 周期: 1m, 5m, 15m, 1h, 4h, 1d
    #[prost(string, tag = "2")]
    pub interval: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub start_time: i64,
    #[prost(int64, tag = "4")]
    pub end_time: i64,
    /// 数量限制
    #[prost(int32, tag = "5")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKlinesResponse {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    #[prost(string, tag = "2")]
    pub interval: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub klines: ::prost::alloc::vec::Vec<KlineData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KlineData {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(string, tag = "2")]
    pub open: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub high: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub low: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub close: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub volume: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub quote_volume: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestKlineRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    #[prost(string, tag = "2")]
    pub interval: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestKlineResponse {
    #[prost(message, optional, tag = "1")]
    pub kline: ::core::option::Option<KlineData>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetRecentTradesRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    /// 可选，指定选项
    #[prost(int64, tag = "2")]
    pub outcome_id: i64,
    /// 数量限制
    #[prost(int32, tag = "3")]
    pub limit: i32,
    /// 分页游标
    #[prost(int64, tag = "4")]
    pub from_trade_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRecentTradesResponse {
    #[prost(message, repeated, tag = "1")]
    pub trades: ::prost::alloc::vec::Vec<TradeData>,
    /// 下次分页游标
    #[prost(int64, tag = "2")]
    pub next_from_trade_id: i64,
    #[prost(bool, tag = "3")]
    pub has_more: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeData {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub market_id: i64,
    #[prost(int64, tag = "3")]
    pub outcome_id: i64,
    #[prost(int64, tag = "4")]
    pub user_id: i64,
    /// buy, sell
    #[prost(string, tag = "5")]
    pub side: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub quantity: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub fee: ::prost::alloc::string::String,
    #[prost(int64, tag = "10")]
    pub timestamp: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Get24hStatsRequest {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Get24hStatsResponse {
    #[prost(int64, tag = "1")]
    pub market_id: i64,
    /// 24h 成交量
    #[prost(string, tag = "2")]
    pub volume_24h: ::prost::alloc::string::String,
    /// 24h 成交额
    #[prost(string, tag = "3")]
    pub amount_24h: ::prost::alloc::string::String,
    /// 24h 最高价
    #[prost(string, tag = "4")]
    pub high_24h: ::prost::alloc::string::String,
    /// 24h 最低价
    #[prost(string, tag = "5")]
    pub low_5h: ::prost::alloc::string::String,
    /// 价格变化
    #[prost(string, tag = "6")]
    pub price_change: ::prost::alloc::string::String,
    /// 价格变化百分比
    #[prost(string, tag = "7")]
    pub price_change_percent: ::prost::alloc::string::String,
    /// 24h 成交笔数
    #[prost(int64, tag = "8")]
    pub trade_count_24h: i64,
    #[prost(int64, tag = "9")]
    pub timestamp: i64,
}
/// Generated client implementations.
pub mod market_data_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MarketDataServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MarketDataServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MarketDataServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MarketDataServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MarketDataServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 市场查询
        pub async fn get_markets(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMarketsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMarketsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetMarkets",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("market_data.MarketDataService", "GetMarkets"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_market_detail(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMarketDetailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMarketDetailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetMarketDetail",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("market_data.MarketDataService", "GetMarketDetail"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 选项价格
        pub async fn get_outcome_prices(
            &mut self,
            request: impl tonic::IntoRequest<super::GetOutcomePricesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOutcomePricesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetOutcomePrices",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("market_data.MarketDataService", "GetOutcomePrices"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 深度/订单簿
        pub async fn get_order_book(
            &mut self,
            request: impl tonic::IntoRequest<super::GetOrderBookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOrderBookResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetOrderBook",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("market_data.MarketDataService", "GetOrderBook"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// K线
        pub async fn get_klines(
            &mut self,
            request: impl tonic::IntoRequest<super::GetKlinesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKlinesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetKlines",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("market_data.MarketDataService", "GetKlines"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_latest_kline(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLatestKlineRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestKlineResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetLatestKline",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("market_data.MarketDataService", "GetLatestKline"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 成交记录
        pub async fn get_recent_trades(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRecentTradesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRecentTradesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/GetRecentTrades",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("market_data.MarketDataService", "GetRecentTrades"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 24h 统计
        pub async fn get24h_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::Get24hStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Get24hStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/market_data.MarketDataService/Get24hStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("market_data.MarketDataService", "Get24hStats"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod market_data_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MarketDataServiceServer.
    #[async_trait]
    pub trait MarketDataService: std::marker::Send + std::marker::Sync + 'static {
        /// 市场查询
        async fn get_markets(
            &self,
            request: tonic::Request<super::GetMarketsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMarketsResponse>,
            tonic::Status,
        >;
        async fn get_market_detail(
            &self,
            request: tonic::Request<super::GetMarketDetailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMarketDetailResponse>,
            tonic::Status,
        >;
        /// 选项价格
        async fn get_outcome_prices(
            &self,
            request: tonic::Request<super::GetOutcomePricesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOutcomePricesResponse>,
            tonic::Status,
        >;
        /// 深度/订单簿
        async fn get_order_book(
            &self,
            request: tonic::Request<super::GetOrderBookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOrderBookResponse>,
            tonic::Status,
        >;
        /// K线
        async fn get_klines(
            &self,
            request: tonic::Request<super::GetKlinesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKlinesResponse>,
            tonic::Status,
        >;
        async fn get_latest_kline(
            &self,
            request: tonic::Request<super::GetLatestKlineRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestKlineResponse>,
            tonic::Status,
        >;
        /// 成交记录
        async fn get_recent_trades(
            &self,
            request: tonic::Request<super::GetRecentTradesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRecentTradesResponse>,
            tonic::Status,
        >;
        /// 24h 统计
        async fn get24h_stats(
            &self,
            request: tonic::Request<super::Get24hStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Get24hStatsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MarketDataServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MarketDataServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MarketDataServiceServer<T>
    where
        T: MarketDataService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/market_data.MarketDataService/GetMarkets" => {
                    #[allow(non_camel_case_types)]
                    struct GetMarketsSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetMarketsRequest>
                    for GetMarketsSvc<T> {
                        type Response = super::GetMarketsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMarketsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_markets(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMarketsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/GetMarketDetail" => {
                    #[allow(non_camel_case_types)]
                    struct GetMarketDetailSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetMarketDetailRequest>
                    for GetMarketDetailSvc<T> {
                        type Response = super::GetMarketDetailResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMarketDetailRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_market_detail(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMarketDetailSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/GetOutcomePrices" => {
                    #[allow(non_camel_case_types)]
                    struct GetOutcomePricesSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetOutcomePricesRequest>
                    for GetOutcomePricesSvc<T> {
                        type Response = super::GetOutcomePricesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetOutcomePricesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_outcome_prices(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetOutcomePricesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/GetOrderBook" => {
                    #[allow(non_camel_case_types)]
                    struct GetOrderBookSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetOrderBookRequest>
                    for GetOrderBookSvc<T> {
                        type Response = super::GetOrderBookResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetOrderBookRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_order_book(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetOrderBookSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/GetKlines" => {
                    #[allow(non_camel_case_types)]
                    struct GetKlinesSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetKlinesRequest>
                    for GetKlinesSvc<T> {
                        type Response = super::GetKlinesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetKlinesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_klines(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetKlinesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/GetLatestKline" => {
                    #[allow(non_camel_case_types)]
                    struct GetLatestKlineSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetLatestKlineRequest>
                    for GetLatestKlineSvc<T> {
                        type Response = super::GetLatestKlineResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLatestKlineRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_latest_kline(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLatestKlineSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/GetRecentTrades" => {
                    #[allow(non_camel_case_types)]
                    struct GetRecentTradesSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::GetRecentTradesRequest>
                    for GetRecentTradesSvc<T> {
                        type Response = super::GetRecentTradesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRecentTradesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_recent_trades(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRecentTradesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/market_data.MarketDataService/Get24hStats" => {
                    #[allow(non_camel_case_types)]
                    struct Get24hStatsSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::Get24hStatsRequest>
                    for Get24hStatsSvc<T> {
                        type Response = super::Get24hStatsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Get24hStatsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get24h_stats(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = Get24hStatsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MarketDataServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "market_data.MarketDataService";
    impl<T> tonic::server::NamedService for MarketDataServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
