// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 创建账户时使用的精度 (仅首次创建有效，已存在则忽略)
    #[prost(int32, tag = "3")]
    pub precision: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub user_id: i64,
    #[prost(string, tag = "5")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "6")]
    pub available: i64,
    /// 最小单位整数
    #[prost(int64, tag = "7")]
    pub frozen: i64,
    /// 最小单位整数
    #[prost(int64, tag = "8")]
    pub locked: i64,
    /// 资产精度 (小数位数)
    #[prost(int32, tag = "9")]
    pub precision: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetBalancesRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalancesResponse {
    #[prost(message, repeated, tag = "1")]
    pub balances: ::prost::alloc::vec::Vec<Balance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Balance {
    #[prost(int64, tag = "1")]
    pub account_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub available: i64,
    /// 最小单位整数
    #[prost(int64, tag = "4")]
    pub frozen: i64,
    /// 最小单位整数
    #[prost(int64, tag = "5")]
    pub locked: i64,
    /// 资产精度 (小数位数)
    #[prost(int32, tag = "6")]
    pub precision: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FreezeRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    /// 创建账户时的精度 (仅首次创建有效)
    #[prost(int32, tag = "6")]
    pub precision: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FreezeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    /// 最小单位整数
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
    #[prost(int64, tag = "6")]
    pub frozen_before: i64,
    #[prost(int64, tag = "7")]
    pub frozen_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnfreezeRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnfreezeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
    #[prost(int64, tag = "6")]
    pub frozen_before: i64,
    #[prost(int64, tag = "7")]
    pub frozen_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FreezeAndDeductRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    /// 基础资产 (USDT)
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 从冻结扣减的金额 (最小单位)
    #[prost(int64, tag = "3")]
    pub freeze_amount: i64,
    /// 实际扣减金额 (最小单位, 可能因部分成交而不同)
    #[prost(int64, tag = "4")]
    pub deduct_amount: i64,
    #[prost(string, tag = "5")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
    /// 结果代币标识 ("{market_id}_{outcome}")
    #[prost(string, tag = "7")]
    pub outcome_asset: ::prost::alloc::string::String,
    /// 结果代币增加数量 (最小单位)
    #[prost(int64, tag = "8")]
    pub outcome_amount: i64,
    /// 结果代币精度 (创建账户时使用)
    #[prost(int32, tag = "9")]
    pub outcome_precision: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FreezeAndDeductResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
    #[prost(int64, tag = "6")]
    pub frozen_before: i64,
    #[prost(int64, tag = "7")]
    pub frozen_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckAndFreezeRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    /// 创建账户时的精度 (仅首次创建有效)
    #[prost(int32, tag = "6")]
    pub precision: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckAndFreezeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
    #[prost(int64, tag = "6")]
    pub frozen_before: i64,
    #[prost(int64, tag = "7")]
    pub frozen_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub withdraw_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferRequest {
    #[prost(int64, tag = "1")]
    pub from_user_id: i64,
    #[prost(int64, tag = "2")]
    pub to_user_id: i64,
    #[prost(string, tag = "3")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "4")]
    pub amount: i64,
    #[prost(string, tag = "5")]
    pub transfer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub from_available_before: i64,
    #[prost(int64, tag = "4")]
    pub from_available_after: i64,
    #[prost(int64, tag = "5")]
    pub to_available_before: i64,
    #[prost(int64, tag = "6")]
    pub to_available_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
    #[prost(int64, tag = "6")]
    pub locked_before: i64,
    #[prost(int64, tag = "7")]
    pub locked_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int64, tag = "4")]
    pub available_before: i64,
    #[prost(int64, tag = "5")]
    pub available_after: i64,
    #[prost(int64, tag = "6")]
    pub locked_before: i64,
    #[prost(int64, tag = "7")]
    pub locked_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckBalanceRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub amount: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckBalanceResponse {
    #[prost(bool, tag = "1")]
    pub sufficient: bool,
    /// 最小单位整数
    #[prost(int64, tag = "2")]
    pub available: i64,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub required: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckFrozenRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub order_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckFrozenResponse {
    #[prost(bool, tag = "1")]
    pub sufficient: bool,
    /// 最小单位整数
    #[prost(int64, tag = "2")]
    pub frozen: i64,
    /// 最小单位整数
    #[prost(int64, tag = "3")]
    pub required: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettleRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    /// 结果代币标识
    #[prost(string, tag = "2")]
    pub outcome_asset: ::prost::alloc::string::String,
    /// 消耗的结果代币数量 (最小单位)
    #[prost(int64, tag = "3")]
    pub outcome_amount: i64,
    /// 基础资产标识 (USDT)
    #[prost(string, tag = "4")]
    pub base_asset: ::prost::alloc::string::String,
    /// 派彩基础资产数量 (最小单位)
    #[prost(int64, tag = "5")]
    pub base_amount: i64,
    #[prost(int64, tag = "6")]
    pub market_id: i64,
    #[prost(string, tag = "7")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettleResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 结算后结果代币可用
    #[prost(int64, tag = "3")]
    pub outcome_available_after: i64,
    /// 结算后基础资产可用
    #[prost(int64, tag = "4")]
    pub base_available_after: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchGetBalancesRequest {
    #[prost(int64, repeated, tag = "1")]
    pub user_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, repeated, tag = "2")]
    pub assets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchGetBalancesResponse {
    #[prost(message, repeated, tag = "1")]
    pub balances: ::prost::alloc::vec::Vec<Balance>,
}
/// Generated server implementations.
pub mod account_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AccountServiceServer.
    #[async_trait]
    pub trait AccountService: std::marker::Send + std::marker::Sync + 'static {
        /// 余额查询
        async fn get_balance(
            &self,
            request: tonic::Request<super::GetBalanceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBalanceResponse>,
            tonic::Status,
        >;
        async fn get_balances(
            &self,
            request: tonic::Request<super::GetBalancesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBalancesResponse>,
            tonic::Status,
        >;
        /// 冻结/解冻 (Order Service 调用)
        async fn freeze(
            &self,
            request: tonic::Request<super::FreezeRequest>,
        ) -> std::result::Result<tonic::Response<super::FreezeResponse>, tonic::Status>;
        async fn unfreeze(
            &self,
            request: tonic::Request<super::UnfreezeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnfreezeResponse>,
            tonic::Status,
        >;
        async fn freeze_and_deduct(
            &self,
            request: tonic::Request<super::FreezeAndDeductRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FreezeAndDeductResponse>,
            tonic::Status,
        >;
        async fn check_and_freeze(
            &self,
            request: tonic::Request<super::CheckAndFreezeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckAndFreezeResponse>,
            tonic::Status,
        >;
        /// 充值/提现 (Wallet Service 调用)
        async fn deposit(
            &self,
            request: tonic::Request<super::DepositRequest>,
        ) -> std::result::Result<tonic::Response<super::DepositResponse>, tonic::Status>;
        async fn withdraw(
            &self,
            request: tonic::Request<super::WithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WithdrawResponse>,
            tonic::Status,
        >;
        /// 划转 (内部服务调用)
        async fn transfer(
            &self,
            request: tonic::Request<super::TransferRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransferResponse>,
            tonic::Status,
        >;
        /// 风控锁定/解锁 (Risk Service 调用)
        async fn lock(
            &self,
            request: tonic::Request<super::LockRequest>,
        ) -> std::result::Result<tonic::Response<super::LockResponse>, tonic::Status>;
        async fn unlock(
            &self,
            request: tonic::Request<super::UnlockRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlockResponse>, tonic::Status>;
        /// 风控查询
        async fn check_balance(
            &self,
            request: tonic::Request<super::CheckBalanceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckBalanceResponse>,
            tonic::Status,
        >;
        async fn check_frozen(
            &self,
            request: tonic::Request<super::CheckFrozenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckFrozenResponse>,
            tonic::Status,
        >;
        /// 结算派彩 (Clearing Service 调用)
        async fn settle(
            &self,
            request: tonic::Request<super::SettleRequest>,
        ) -> std::result::Result<tonic::Response<super::SettleResponse>, tonic::Status>;
        /// 批量操作 (用于对账)
        async fn batch_get_balances(
            &self,
            request: tonic::Request<super::BatchGetBalancesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchGetBalancesResponse>,
            tonic::Status,
        >;
    }
    /// Account Service - 账户余额管理服务
    /// 支持: USDT 基础资产 + {market_id}_{outcome} 结果代币
    #[derive(Debug)]
    pub struct AccountServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AccountServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AccountServiceServer<T>
    where
        T: AccountService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/account.AccountService/GetBalance" => {
                    #[allow(non_camel_case_types)]
                    struct GetBalanceSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::GetBalanceRequest>
                    for GetBalanceSvc<T> {
                        type Response = super::GetBalanceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBalanceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::get_balance(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBalanceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/GetBalances" => {
                    #[allow(non_camel_case_types)]
                    struct GetBalancesSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::GetBalancesRequest>
                    for GetBalancesSvc<T> {
                        type Response = super::GetBalancesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBalancesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::get_balances(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBalancesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Freeze" => {
                    #[allow(non_camel_case_types)]
                    struct FreezeSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::FreezeRequest>
                    for FreezeSvc<T> {
                        type Response = super::FreezeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FreezeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::freeze(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FreezeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Unfreeze" => {
                    #[allow(non_camel_case_types)]
                    struct UnfreezeSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::UnfreezeRequest>
                    for UnfreezeSvc<T> {
                        type Response = super::UnfreezeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnfreezeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::unfreeze(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnfreezeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/FreezeAndDeduct" => {
                    #[allow(non_camel_case_types)]
                    struct FreezeAndDeductSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::FreezeAndDeductRequest>
                    for FreezeAndDeductSvc<T> {
                        type Response = super::FreezeAndDeductResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FreezeAndDeductRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::freeze_and_deduct(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FreezeAndDeductSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/CheckAndFreeze" => {
                    #[allow(non_camel_case_types)]
                    struct CheckAndFreezeSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::CheckAndFreezeRequest>
                    for CheckAndFreezeSvc<T> {
                        type Response = super::CheckAndFreezeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckAndFreezeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::check_and_freeze(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckAndFreezeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Deposit" => {
                    #[allow(non_camel_case_types)]
                    struct DepositSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::DepositRequest>
                    for DepositSvc<T> {
                        type Response = super::DepositResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DepositRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::deposit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DepositSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Withdraw" => {
                    #[allow(non_camel_case_types)]
                    struct WithdrawSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::WithdrawRequest>
                    for WithdrawSvc<T> {
                        type Response = super::WithdrawResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WithdrawRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::withdraw(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WithdrawSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Transfer" => {
                    #[allow(non_camel_case_types)]
                    struct TransferSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::TransferRequest>
                    for TransferSvc<T> {
                        type Response = super::TransferResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TransferRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::transfer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TransferSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Lock" => {
                    #[allow(non_camel_case_types)]
                    struct LockSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::LockRequest> for LockSvc<T> {
                        type Response = super::LockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::lock(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LockSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Unlock" => {
                    #[allow(non_camel_case_types)]
                    struct UnlockSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::UnlockRequest>
                    for UnlockSvc<T> {
                        type Response = super::UnlockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnlockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::unlock(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnlockSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/CheckBalance" => {
                    #[allow(non_camel_case_types)]
                    struct CheckBalanceSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::CheckBalanceRequest>
                    for CheckBalanceSvc<T> {
                        type Response = super::CheckBalanceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckBalanceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::check_balance(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckBalanceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/CheckFrozen" => {
                    #[allow(non_camel_case_types)]
                    struct CheckFrozenSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::CheckFrozenRequest>
                    for CheckFrozenSvc<T> {
                        type Response = super::CheckFrozenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckFrozenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::check_frozen(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckFrozenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/Settle" => {
                    #[allow(non_camel_case_types)]
                    struct SettleSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::SettleRequest>
                    for SettleSvc<T> {
                        type Response = super::SettleResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SettleRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::settle(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SettleSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/account.AccountService/BatchGetBalances" => {
                    #[allow(non_camel_case_types)]
                    struct BatchGetBalancesSvc<T: AccountService>(pub Arc<T>);
                    impl<
                        T: AccountService,
                    > tonic::server::UnaryService<super::BatchGetBalancesRequest>
                    for BatchGetBalancesSvc<T> {
                        type Response = super::BatchGetBalancesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchGetBalancesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccountService>::batch_get_balances(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchGetBalancesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AccountServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "account.AccountService";
    impl<T> tonic::server::NamedService for AccountServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
