// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDepositAddressRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDepositAddressResponse {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListDepositAddressesRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDepositAddressesResponse {
    #[prost(message, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<DepositAddressSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositAddressSummary {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmDepositRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub chain: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmDepositResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDepositHistoryRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDepositHistoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub deposits: ::prost::alloc::vec::Vec<DepositRecord>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositRecord {
    #[prost(string, tag = "1")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub address: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWithdrawRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub to_address: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub chain: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub payment_password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWithdrawResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub withdraw_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmWithdrawRequest {
    #[prost(string, tag = "1")]
    pub withdraw_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub otp_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmWithdrawResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tx_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelWithdrawRequest {
    #[prost(string, tag = "1")]
    pub withdraw_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelWithdrawResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetWithdrawHistoryRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWithdrawHistoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub withdrawals: ::prost::alloc::vec::Vec<WithdrawRecordSummary>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawRecordSummary {
    #[prost(string, tag = "1")]
    pub withdraw_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub fee: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub to_address: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetPendingWithdrawsRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPendingWithdrawsResponse {
    #[prost(message, repeated, tag = "1")]
    pub withdrawals: ::prost::alloc::vec::Vec<WithdrawRecordSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddWhitelistAddressRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub label: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddWhitelistAddressResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveWhitelistAddressRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveWhitelistAddressResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWhitelistAddressesRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub chain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWhitelistAddressesResponse {
    #[prost(message, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<WhitelistAddressSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhitelistAddressSummary {
    #[prost(string, tag = "1")]
    pub chain: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IsWhitelistedRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsWhitelistedResponse {
    #[prost(bool, tag = "1")]
    pub is_whitelisted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPaymentPasswordRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPaymentPasswordResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyPaymentPasswordRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyPaymentPasswordResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResetPaymentPasswordRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub old_password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResetPaymentPasswordResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HasPaymentPasswordRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HasPaymentPasswordResponse {
    #[prost(bool, tag = "1")]
    pub has_password: bool,
}
/// Generated client implementations.
pub mod wallet_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct WalletServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WalletServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WalletServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WalletServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WalletServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// ========== 充值地址 ==========
        pub async fn get_deposit_address(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDepositAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDepositAddressResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/GetDepositAddress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "GetDepositAddress"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_deposit_addresses(
            &mut self,
            request: impl tonic::IntoRequest<super::ListDepositAddressesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDepositAddressesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/ListDepositAddresses",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "ListDepositAddresses"));
            self.inner.unary(req, path, codec).await
        }
        /// ========== 充值 ==========
        pub async fn confirm_deposit(
            &mut self,
            request: impl tonic::IntoRequest<super::ConfirmDepositRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfirmDepositResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/ConfirmDeposit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "ConfirmDeposit"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_deposit_history(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDepositHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDepositHistoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/GetDepositHistory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "GetDepositHistory"));
            self.inner.unary(req, path, codec).await
        }
        /// ========== 提现 ==========
        pub async fn create_withdraw(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateWithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateWithdrawResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/CreateWithdraw",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "CreateWithdraw"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn confirm_withdraw(
            &mut self,
            request: impl tonic::IntoRequest<super::ConfirmWithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfirmWithdrawResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/ConfirmWithdraw",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "ConfirmWithdraw"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_withdraw(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelWithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelWithdrawResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/CancelWithdraw",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "CancelWithdraw"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_withdraw_history(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWithdrawHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWithdrawHistoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/GetWithdrawHistory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "GetWithdrawHistory"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_pending_withdraws(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPendingWithdrawsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPendingWithdrawsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/GetPendingWithdraws",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "GetPendingWithdraws"));
            self.inner.unary(req, path, codec).await
        }
        /// ========== 地址白名单 ==========
        pub async fn add_whitelist_address(
            &mut self,
            request: impl tonic::IntoRequest<super::AddWhitelistAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddWhitelistAddressResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/AddWhitelistAddress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "AddWhitelistAddress"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn remove_whitelist_address(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveWhitelistAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveWhitelistAddressResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/RemoveWhitelistAddress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("wallet.WalletService", "RemoveWhitelistAddress"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_whitelist_addresses(
            &mut self,
            request: impl tonic::IntoRequest<super::ListWhitelistAddressesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListWhitelistAddressesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/ListWhitelistAddresses",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("wallet.WalletService", "ListWhitelistAddresses"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn is_whitelisted(
            &mut self,
            request: impl tonic::IntoRequest<super::IsWhitelistedRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IsWhitelistedResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/IsWhitelisted",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "IsWhitelisted"));
            self.inner.unary(req, path, codec).await
        }
        /// ========== 支付密码 ==========
        pub async fn set_payment_password(
            &mut self,
            request: impl tonic::IntoRequest<super::SetPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPaymentPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/SetPaymentPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "SetPaymentPassword"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn verify_payment_password(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyPaymentPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/VerifyPaymentPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("wallet.WalletService", "VerifyPaymentPassword"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn reset_payment_password(
            &mut self,
            request: impl tonic::IntoRequest<super::ResetPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResetPaymentPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/ResetPaymentPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "ResetPaymentPassword"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn has_payment_password(
            &mut self,
            request: impl tonic::IntoRequest<super::HasPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasPaymentPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/wallet.WalletService/HasPaymentPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("wallet.WalletService", "HasPaymentPassword"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod wallet_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with WalletServiceServer.
    #[async_trait]
    pub trait WalletService: std::marker::Send + std::marker::Sync + 'static {
        /// ========== 充值地址 ==========
        async fn get_deposit_address(
            &self,
            request: tonic::Request<super::GetDepositAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDepositAddressResponse>,
            tonic::Status,
        >;
        async fn list_deposit_addresses(
            &self,
            request: tonic::Request<super::ListDepositAddressesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDepositAddressesResponse>,
            tonic::Status,
        >;
        /// ========== 充值 ==========
        async fn confirm_deposit(
            &self,
            request: tonic::Request<super::ConfirmDepositRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfirmDepositResponse>,
            tonic::Status,
        >;
        async fn get_deposit_history(
            &self,
            request: tonic::Request<super::GetDepositHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDepositHistoryResponse>,
            tonic::Status,
        >;
        /// ========== 提现 ==========
        async fn create_withdraw(
            &self,
            request: tonic::Request<super::CreateWithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateWithdrawResponse>,
            tonic::Status,
        >;
        async fn confirm_withdraw(
            &self,
            request: tonic::Request<super::ConfirmWithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfirmWithdrawResponse>,
            tonic::Status,
        >;
        async fn cancel_withdraw(
            &self,
            request: tonic::Request<super::CancelWithdrawRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelWithdrawResponse>,
            tonic::Status,
        >;
        async fn get_withdraw_history(
            &self,
            request: tonic::Request<super::GetWithdrawHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWithdrawHistoryResponse>,
            tonic::Status,
        >;
        async fn get_pending_withdraws(
            &self,
            request: tonic::Request<super::GetPendingWithdrawsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPendingWithdrawsResponse>,
            tonic::Status,
        >;
        /// ========== 地址白名单 ==========
        async fn add_whitelist_address(
            &self,
            request: tonic::Request<super::AddWhitelistAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddWhitelistAddressResponse>,
            tonic::Status,
        >;
        async fn remove_whitelist_address(
            &self,
            request: tonic::Request<super::RemoveWhitelistAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveWhitelistAddressResponse>,
            tonic::Status,
        >;
        async fn list_whitelist_addresses(
            &self,
            request: tonic::Request<super::ListWhitelistAddressesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListWhitelistAddressesResponse>,
            tonic::Status,
        >;
        async fn is_whitelisted(
            &self,
            request: tonic::Request<super::IsWhitelistedRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IsWhitelistedResponse>,
            tonic::Status,
        >;
        /// ========== 支付密码 ==========
        async fn set_payment_password(
            &self,
            request: tonic::Request<super::SetPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPaymentPasswordResponse>,
            tonic::Status,
        >;
        async fn verify_payment_password(
            &self,
            request: tonic::Request<super::VerifyPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyPaymentPasswordResponse>,
            tonic::Status,
        >;
        async fn reset_payment_password(
            &self,
            request: tonic::Request<super::ResetPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResetPaymentPasswordResponse>,
            tonic::Status,
        >;
        async fn has_payment_password(
            &self,
            request: tonic::Request<super::HasPaymentPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasPaymentPasswordResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct WalletServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> WalletServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for WalletServiceServer<T>
    where
        T: WalletService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/wallet.WalletService/GetDepositAddress" => {
                    #[allow(non_camel_case_types)]
                    struct GetDepositAddressSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::GetDepositAddressRequest>
                    for GetDepositAddressSvc<T> {
                        type Response = super::GetDepositAddressResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetDepositAddressRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::get_deposit_address(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDepositAddressSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/ListDepositAddresses" => {
                    #[allow(non_camel_case_types)]
                    struct ListDepositAddressesSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::ListDepositAddressesRequest>
                    for ListDepositAddressesSvc<T> {
                        type Response = super::ListDepositAddressesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListDepositAddressesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::list_deposit_addresses(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListDepositAddressesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/ConfirmDeposit" => {
                    #[allow(non_camel_case_types)]
                    struct ConfirmDepositSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::ConfirmDepositRequest>
                    for ConfirmDepositSvc<T> {
                        type Response = super::ConfirmDepositResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ConfirmDepositRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::confirm_deposit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConfirmDepositSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/GetDepositHistory" => {
                    #[allow(non_camel_case_types)]
                    struct GetDepositHistorySvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::GetDepositHistoryRequest>
                    for GetDepositHistorySvc<T> {
                        type Response = super::GetDepositHistoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetDepositHistoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::get_deposit_history(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDepositHistorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/CreateWithdraw" => {
                    #[allow(non_camel_case_types)]
                    struct CreateWithdrawSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::CreateWithdrawRequest>
                    for CreateWithdrawSvc<T> {
                        type Response = super::CreateWithdrawResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateWithdrawRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::create_withdraw(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateWithdrawSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/ConfirmWithdraw" => {
                    #[allow(non_camel_case_types)]
                    struct ConfirmWithdrawSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::ConfirmWithdrawRequest>
                    for ConfirmWithdrawSvc<T> {
                        type Response = super::ConfirmWithdrawResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ConfirmWithdrawRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::confirm_withdraw(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConfirmWithdrawSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/CancelWithdraw" => {
                    #[allow(non_camel_case_types)]
                    struct CancelWithdrawSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::CancelWithdrawRequest>
                    for CancelWithdrawSvc<T> {
                        type Response = super::CancelWithdrawResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelWithdrawRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::cancel_withdraw(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelWithdrawSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/GetWithdrawHistory" => {
                    #[allow(non_camel_case_types)]
                    struct GetWithdrawHistorySvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::GetWithdrawHistoryRequest>
                    for GetWithdrawHistorySvc<T> {
                        type Response = super::GetWithdrawHistoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetWithdrawHistoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::get_withdraw_history(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetWithdrawHistorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/GetPendingWithdraws" => {
                    #[allow(non_camel_case_types)]
                    struct GetPendingWithdrawsSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::GetPendingWithdrawsRequest>
                    for GetPendingWithdrawsSvc<T> {
                        type Response = super::GetPendingWithdrawsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPendingWithdrawsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::get_pending_withdraws(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPendingWithdrawsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/AddWhitelistAddress" => {
                    #[allow(non_camel_case_types)]
                    struct AddWhitelistAddressSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::AddWhitelistAddressRequest>
                    for AddWhitelistAddressSvc<T> {
                        type Response = super::AddWhitelistAddressResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddWhitelistAddressRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::add_whitelist_address(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddWhitelistAddressSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/RemoveWhitelistAddress" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveWhitelistAddressSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::RemoveWhitelistAddressRequest>
                    for RemoveWhitelistAddressSvc<T> {
                        type Response = super::RemoveWhitelistAddressResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveWhitelistAddressRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::remove_whitelist_address(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveWhitelistAddressSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/ListWhitelistAddresses" => {
                    #[allow(non_camel_case_types)]
                    struct ListWhitelistAddressesSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::ListWhitelistAddressesRequest>
                    for ListWhitelistAddressesSvc<T> {
                        type Response = super::ListWhitelistAddressesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListWhitelistAddressesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::list_whitelist_addresses(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListWhitelistAddressesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/IsWhitelisted" => {
                    #[allow(non_camel_case_types)]
                    struct IsWhitelistedSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::IsWhitelistedRequest>
                    for IsWhitelistedSvc<T> {
                        type Response = super::IsWhitelistedResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IsWhitelistedRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::is_whitelisted(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IsWhitelistedSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/SetPaymentPassword" => {
                    #[allow(non_camel_case_types)]
                    struct SetPaymentPasswordSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::SetPaymentPasswordRequest>
                    for SetPaymentPasswordSvc<T> {
                        type Response = super::SetPaymentPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetPaymentPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::set_payment_password(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetPaymentPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/VerifyPaymentPassword" => {
                    #[allow(non_camel_case_types)]
                    struct VerifyPaymentPasswordSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::VerifyPaymentPasswordRequest>
                    for VerifyPaymentPasswordSvc<T> {
                        type Response = super::VerifyPaymentPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyPaymentPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::verify_payment_password(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VerifyPaymentPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/ResetPaymentPassword" => {
                    #[allow(non_camel_case_types)]
                    struct ResetPaymentPasswordSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::ResetPaymentPasswordRequest>
                    for ResetPaymentPasswordSvc<T> {
                        type Response = super::ResetPaymentPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResetPaymentPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::reset_payment_password(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResetPaymentPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/wallet.WalletService/HasPaymentPassword" => {
                    #[allow(non_camel_case_types)]
                    struct HasPaymentPasswordSvc<T: WalletService>(pub Arc<T>);
                    impl<
                        T: WalletService,
                    > tonic::server::UnaryService<super::HasPaymentPasswordRequest>
                    for HasPaymentPasswordSvc<T> {
                        type Response = super::HasPaymentPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HasPaymentPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WalletService>::has_payment_password(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HasPaymentPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for WalletServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "wallet.WalletService";
    impl<T> tonic::server::NamedService for WalletServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
